import * as atoms from './atoms';
import * as condition from './condition';
import * as prompt from './prompt';
import * as respond from './respond';
import * as loop from './loop';
import * as emit from './emit';
import * as foreach from './foreach';
import * as checkDying from './checkDying';
import * as pindian from './pindian';
import * as multiStep from './multiStep';

atoms.register();
condition.register();
prompt.register();
respond.register();
loop.register();
emit.register();
foreach.register();
checkDying.register();
pindian.register();
multiStep.register();
