import * as damage from './damage';
import * as draw from './draw';
import * as heal from './heal';
import * as discard from './discard';
import * as discardRandom from './discardRandom';
import * as moveCard from './moveCard';
import * as equip from './equip';
import * as varModule from './var';
import * as phase from './phase';
import * as tag from './tag';
import * as pending from './pending';
import * as judge from './judge';
import * as pendingTrick from './pendingTrick';
import * as kill from './kill';
import * as gainCard from './gainCard';
import * as ctxVar from './ctxVar';
import * as turn from './turn';
import * as rearrangeDeck from './rearrangeDeck';

damage.register();
draw.register();
heal.register();
discard.register();
discardRandom.register();
moveCard.register();
equip.register();
varModule.register();
phase.register();
tag.register();
pending.register();
judge.register();
pendingTrick.register();
kill.register();
gainCard.register();
ctxVar.register();
turn.register();
rearrangeDeck.register();
