// src/engine/skills/index.ts
// 一次性 import 所有 skill 模块(注册副作用)
import './杀';
import './闪';
import './桃';
import './酒';
import './仁德';
import './激将';
import './护甲';
import './制衡';
import './武圣';
import './遗计';
import './回合管理';
import './八卦阵';
import './流离';
import './南蛮入侵';
import './万箭齐发';
import './决斗';
import './反馈';
// 武器
import './诸葛连弩';
import './青釭剑';
import './青龙偃月刀';
import './雌雄双股剑';
import './贯石斧';
import './丈八蛇矛';
import './方天画戟';
import './寒冰剑';
// 防具/延时锦囊
import './仁王盾';
import './藤甲';
import './白银狮子';
import './乐不思蜀';
// 即时锦囊
import './过河拆桥';
import './顺手牵羊';
import './无中生有';
import './桃园结义';
import './借刀杀人';
import './无懈可击';
// 通用
import './装备通用';
